#!/bin/bash
###
#
# file    remarkableBackup
# author  Rodrigo Pedroso Mendes
# version V1.0
# date    31/01/23 18:57:19
# brief   Copy all files available in the remakable tablet to a folder
# 
# Copyright (c) 2023 Rodrigo Pedroso Mendes
#
# Permission is hereby granted, free of charge, to any  person   obtaining  a 
# copy of this software and associated  documentation files (the "Software"), 
# to deal in the Software without restriction, including  without  limitation 
# the rights to use, copy, modify,  merge,  publish,  distribute, sublicense, 
# and/or sell copies of the Software, and  to  permit  persons  to  whom  the 
# Software is furnished to do so, subject to the following conditions:        
# 
# The above copyright notice and this permission notice shall be included  in 
# all copies or substantial portions of the Software.                         
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,  EXPRESS OR 
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE  WARRANTIES  OF  MERCHANTABILITY, 
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE 
# AUTHORS OR COPYRIGHT HOLDERS BE  LIABLE FOR ANY  CLAIM,  DAMAGES  OR  OTHER 
# LIABILITY, WHETHER IN AN ACTION OF  CONTRACT, TORT  OR  OTHERWISE,  ARISING 
# FROM, OUT OF OR IN CONNECTION  WITH  THE  SOFTWARE  OR  THE  USE  OR  OTHER 
# DEALINGS IN THE SOFTWARE. 
# 
################################################################################

#-------------------------------------------------------------------------------
# Check input comments
#-------------------------------------------------------------------------------
if [ -z "$1" ]; then
    echo -e "\nPlease call '$0 <argument>' to run this command!\n"
    exit 1
fi

#-------------------------------------------------------------------------------
# Run Backup
#-------------------------------------------------------------------------------
rm -rf $1
mkdir  $1
scp -r root@remarkable:~/.local/share/remarkable/xochitl/*.metadata $1
python3 remarkableBackup.py $1
rm -rf $1/*.metadata
